### ISSUE TITLE
SyntaxError: Invalid regular expression: /\/: \ at end of pattern

### ISSUE THREAD

**Issue by ghost** [bevacqua/shots#12]
When I run `shots wikipedia.org -o wikipedia.gif`I get:

```
C:\Users\Algemeen\AppData\Roaming\npm\node_modules\shots\index.js:75
var rsep = new RegExp(_path.sep, 'g');
           ^

SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at new RegExp (native)
    at Object.<anonymous> (C:\Users\Algemeen\AppData\Roaming\npm\node_modules\shots\index.js:75:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Algemeen\AppData\Roaming\npm\node_modules\shots\cli:17:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

**Comment by ghost** [comment]
chaing it to 
`var rsep = new RegExp('\\' + _path.sep, 'g');
`
fixed it for me

**Comment by Systematic-Bello** [comment]
Hi Guys, I have similar problem, i got an error while compiling my code, what can i do to rectify the problem, because i have tried all my best, but not getting anything so far. The error is as follows:
==========================
C:\Users\Systematic Bello\AppData\Roaming\npm\node_modules\truffle\node_modules\solc\soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var r

SyntaxError: Invalid regular expression: /C:\Users\Systematic Bello\AppData\Roaming\npm\node_modules\/: \
at end of pattern
    at new RegExp (<anonymous>)
    at C:\Users\Systematic Bello\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle--core\cli.js:93:1
    at Object.<anonymous> (C:\Users\Systematic Bello\AppData\Roaming\npm\node_modules\truffle\build\webpacck:\packages\truffle-core\lib\commands\migrate.js:168:1)
    at cb (util.js:354:39)
    at callbackifyOnRejected (util.js:338:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
