### ISSUE TITLE
usage??

### ISSUE THREAD

**Issue by deemyboy** [bevacqua/shots#2]
How do you use it?

Do you write a script?

There is a sample script but absolutely no explanation of how or where to use this?

Do you need to run it using python?

I'm on a mac (el capitan) - do I have to google this?

**Comment by bevacqua** [comment]
Download node and run the sample script after installing shots via npm. It's all in the readme

**Comment by bevacqua** [comment]
cli may be coming

**Comment by deemyboy** [comment]
i have node installed

i'm a new angular dev - switching from php

so in terminal what do i do?

BTW i found this thread for running python scripts

http://forums.macrumors.com/threads/python-syntax-error.1010808/

at the moment i have a python terminal window
i'm going to past your usage script their modified to my site - rentandride.co.uk

**Comment by deemyboy** [comment]
> > > import shots from 'shots';

shots({
  dest: 'resources/shots',
  site: 'rentandride.co.uk'
});
SyntaxError: invalid syntax


as you can see it didn't work!

**Comment by deemyboy** [comment]
i got an error btw when installing shots

# 

canvas@1.3.12 install /usr/local/bin/node_modules/canvas

> node-gyp rebuild

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error:`gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/bin/node_modules/canvas
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/bin/package.json'
npm WARN bin No description
npm WARN bin No repository field.
npm WARN bin No README data
npm WARN bin No license field.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "shots" "-S"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.3.12 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/bin/npm-debug.log

# 

i aslo get this error when trying to use your statement 

# 

nadeems-MacBook-Pro:wayback deemyboy$ import shots from 'shots';
-bash: import: command not found
nadeems-MacBook-Pro:wayback deemyboy$ 

# 

is that related to shots not installing correctly?

**Comment by jimthedev** [comment]
@deemyboy for your canvas error you will need to install cairo.

You can see more in [this](http://stackoverflow.com/questions/22100213/package-cairo-was-not-found-in-the-pkg-config-search-path-node-j-s-install-canv) thread.

If you are using vanilla node and not ES6 modules as shown in the sample then you can use the following:

```
var shots = require('shots').default;

shots({
dest: 'resources/shots',
site: 'rentandride.co.uk'
});
```

**Comment by deemyboy** [comment]
OK,

Even though there were errors during the install?

**Comment by jimthedev** [comment]
To fix the errors during install you need to first install Cairo.

To fix the runtime errors you need to modify the example to use the require().default syntax.

You probably need to do both. I did.

**Comment by jimthedev** [comment]
also, make sure you run `npm install -S shots@latest` as @bevacqua has recently fixed some bugs.

**Comment by deemyboy** [comment]
Cool. Can't wait to get this working.
I started rentandride.co.uk in 2012 when I left uni

**Comment by bevacqua** [comment]
Once you get the install working you probably would rather use the cli, e.g `shots rentandride.co.uk --verbose`

**Comment by Mareeck** [comment]
Hey, I'm not familiar with node at all and just wanted to see that thing in action but I think I'm missing something here. After install I'm supposed to be able to just run shots from the terminal right? It's all probably pretty obvious to someone who uses it everyday. All I did was run the install as described in the readme and then tried to just run shots from the terminal, command not found :/

**Comment by nujabse** [comment]
@bevacqua should I install shots with the npm -g flag to use it on the command line?

**Comment by jimthedev** [comment]
@nujabse 

Yes, generally speaking -g should by used to make it available on the command line. This is the case if you installed node using Homebrew, nvm, or built it from source so that you'd have a copy that is local to your user and does not require sudo (admin) access.

The only exception to this would be if you have node installed globally on your system. This is the case if you downloaded the node binary from the Node website and put in your sudo (admin) password in order to install it.

In that case you'd need to run:

`sudo npm install -g shots`

Please note that you should not add `sudo` in front of install commands unless you are sure that you installed node globally.

For more info see: http://blog.teamtreehouse.com/install-node-js-npm-mac

**Comment by nujabse** [comment]
@jimthedev thanks for the help!

**Comment by deemyboy** [comment]
this isn't working still

installed cairo on my using Macports - all good!

Then I tried 

npm install -S shots@latest 
and 
sudo npm install -g shots

but i get this error - cairo path problem

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found

and

npm ERR! Failed at the canvas@1.3.12 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/deemyboy/npm-debug.log

**Comment by deemyboy** [comment]
@nujabse - are you on Mac or Windows?

I'm on Windows el Capitan.

Is yours working now?

**Comment by deemyboy** [comment]
I've created an environment var called PKG_CONFIG_PATH and set it to :
/opt/X11/lib/pkgconfig where cairo.pc resides but this not resolving the issue!

**Comment by jimthedev** [comment]
Wait, what? Are you on Windows or OSX Capitan?

**Comment by deemyboy** [comment]
OSX El Capitan

Sorry, forgot to say!

MacBook Pro

Sorry, I just saw my previous comment - "Windows el Capitan" - doh!

**Comment by nujabse** [comment]
I'm currently running on archlinux, and the simple " npm i shots -S "
command worked just fine. No cairo problem.

On Sat, May 7, 2016, 11:44 PM deemyboy notifications@github.com wrote:

> @nujabse https://github.com/nujabse - are you on Mac or Windows?
> 
> I'm on Windows el Capitan.
> 
> Is yours working now?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/bevacqua/shots/issues/2#issuecomment-217646058
> 
> ## 

sent from inbox by Gmail

**Comment by deemyboy** [comment]
oooooh....almost there!

Successfully installed waybackpack-0.1.1
nadeems-MacBook-Pro:wayback deemyboy$ shots rentandride.co.uk -o /Applications/MAMP/htdocs/wayback/resources/
{ [Error: spawn identify ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn identify',
  path: 'identify',
  spawnargs: 
   [ '-ping',
     '-format',
     '%wx%h ',
     '/Applications/MAMP/htdocs/wayback/resources/screenshots/rentandride-co-uk-20130701130846-1024x768.html.png' ] }

I get 8 or 10 pngs in the screenshots folder and the same number of html files in the pages folder but no aimated gifs yet,,,SOOOOO close!

Can anyone help with this error?

### A post on SO said this for the above error

# 

http://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js

How do I debug “Error: spawn ENOENT” on node.js?

77 accepted
I found a particular easy way to get the idea of the root cause of:

Error: spawn ENOENT
The problem of this error is, there is really little information in the error message to tell you where the call site is, i.e. which executable/command is not found, especially when you have a large code base where there are a lot of spawn calls. On the other hand, if we know the exact command that cause the error then we can follow @laconbass' answer to fix the problem.

I found a very easy way to spot which command cause the problem rather than adding event listeners everywhere in your code as suggested in @laconbass' answer. The key idea is to wrap the original spawn call with a wrapper which prints the arguments send to the spawn call.

Here is the wrapper function, put it at the top of the index.js or whatever your server's starting script.

(function() {
    var childProcess = require("child_process");
    var oldSpawn = childProcess.spawn;
    function mySpawn() {
        console.log('spawn called');
        console.log(arguments);
        var result = oldSpawn.apply(this, arguments);
        return result;
    }
    childProcess.spawn = mySpawn;
})();
Then the next time you run your application, before the uncaught exception's message you will see something like that:

spawn called
{ '0': 'hg',
  '1': [],
  '2':
   { cwd: '/\* omitted */',
     env: { IP: '0.0.0.0' },
     args: [] } }
In this way you can easily know which command actually is executed and then you can find out why nodejs cannot find the executable to fix the problem.

# 

### I can't see where to add this wrapper ie. which file

**Comment by jimthedev** [comment]
This problem was fixed in latest. Make sure you run npm install -g
shots@latest

**Comment by deemyboy** [comment]
same error

# 

nadeems-MacBook-Pro:~ deemyboy$ npm install -g shots@latest
/usr/local/bin/shots -> /usr/local/lib/node_modules/shots/cli
/usr/local/lib
└── shots@1.3.1 

nadeems-MacBook-Pro:~ deemyboy$ npm update all
nadeems-MacBook-Pro:~ deemyboy$ shots rentandride.co.uk -o /Applications/MAMP/htdocs/wayback/resources/
{ [Error: spawn identify ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn identify',
  path: 'identify',
  spawnargs: 
   [ '-ping',
     '-format',
     '%wx%h ',
     '/Applications/MAMP/htdocs/wayback/resources/screenshots/rentandride-co-uk-20130701130846-1024x768.html.png' ] }

#

**Comment by jimthedev** [comment]
What is the output of 'which shots'?

**Comment by deemyboy** [comment]
nadeems-MacBook-Pro:app deemyboy$ which shots
/usr/local/bin/shots
nadeems-MacBook-Pro:app deemyboy$

**Comment by deemyboy** [comment]
symlink to ../lib/node_modules/shots

nadeems-MacBook-Pro:shots deemyboy$ ls -la
total 120
drwxr-xr-x   12 deemyboy  wheel    408  8 May 17:39 .
drwxrwxr-x   25 deemyboy  wheel    850  8 May 17:39 ..
-rw-r--r--    1 deemyboy  wheel    207  4 May 01:57 .editorconfig
-rw-r--r--    1 deemyboy  wheel     78  4 May 15:35 .eslintrc.json
-rw-r--r--    1 deemyboy  wheel      7  5 May 15:10 .npmignore
-rwxr-xr-x    1 deemyboy  wheel   2072  6 May 02:35 cli
-rw-r--r--    1 deemyboy  wheel   9573  6 May 03:45 index.babel.js
-rw-r--r--    1 deemyboy  wheel  15243  6 May 03:45 index.js
-rw-r--r--    1 deemyboy  wheel   1082  4 May 01:57 license
drwxr-xr-x  239 deemyboy  wheel   8126  8 May 17:39 node_modules
-rw-r--r--    1 deemyboy  wheel   2394  8 May 17:39 package.json
-rw-r--r--    1 deemyboy  wheel   5161  6 May 02:35 readme.markdown
nadeems-MacBook-Pro:shots deemyboy$

**Comment by deemyboy** [comment]
### shots rentandride.co.uk - why don't you run it and send me the animated gif!

# loooooool

**Comment by deemyboy** [comment]
anymore ideas?

**Comment by deemyboy** [comment]
Never got this sorted, can't even remember what "Shots" is tbh

**Comment by lorenzogrv** [comment]
Please see https://stackoverflow.com/a/62551786/1894803

Use `NODE_DEBUG=child_process` to understand what is going on with those spawn calls
